### ISSUE TITLE
Chưa có dòng description, tag khi khai báo project

### ISSUE THREAD

**Issue by congto** [hocchudong/netbox-project-quota#5]
Hiện chưa có mục để nhập descript, tag khi khai báo project nên không sử dụng được thông tin này.

## Khia khai báo project 

![image](https://user-images.githubusercontent.com/5918118/226275792-843185ad-bd0d-4d7d-ae5c-46ef25ce1f16.png)

## Khi view

![image](https://user-images.githubusercontent.com/5918118/226276059-e03e2819-8fc6-49f5-ae78-d5a599ac5592.png)

**Comment by hungviet99** [comment]
Đã có khai bóa description và tag ạ
![image](https://user-images.githubusercontent.com/44610020/226496387-71fdc707-777a-4864-8f11-95bf0dbeebe0.png)


Done!
