### ISSUE TITLE
Chỉ dùng trường name là yêu cầu bắt buộc

### ISSUE THREAD

**Issue by congto** [hocchudong/netbox-project-quota#8]
@hungviet99 

Phần bắt buộc phải nhập trong quota template chỉ cần Name vì nhiều dự án có các tài nguyên khác nhau.

![image](https://user-images.githubusercontent.com/5918118/226277337-c9e1e5b2-2240-4b76-bf2c-a727d4358b6b.png)

**Comment by hungviet99** [comment]
![image](https://user-images.githubusercontent.com/44610020/226403702-62925ef3-ba2c-4663-a279-6036e684ff42.png)

**Comment by hungviet99** [comment]
Done

**Comment by congto** [comment]
ok
